[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "django_sy_framework"
version = "0.1.8"
requires-python = ">=3.11"
description = "framework for microservice's ecosystem"
