# Generated by Django 4.2.1 on 2023-08-31 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_to', models.CharField(max_length=15, verbose_name='Тип объекта, к которому привязываем')),
                ('link_to_id', models.PositiveIntegerField(verbose_name='ID объекта, к которому привязываем')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID привязанного объекта')),
                ('content_type', models.ForeignKey(help_text='Тип привязанного объекта', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Привязанный объект',
                'verbose_name_plural': 'Привязанные объекты',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='index_content_type_linker')],
            },
        ),
        migrations.AddConstraint(
            model_name='linker',
            constraint=models.UniqueConstraint(fields=('link_to', 'link_to_id', 'content_type', 'object_id'), name='unique_linker'),
        ),
    ]
