# Generated by Django 4.2.1 on 2023-11-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempTokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_hash', models.CharField(max_length=32)),
                ('temp_token', models.CharField(max_length=32)),
                ('public_key', models.TextField(max_length=10000)),
                ('private_key', models.TextField(max_length=10000)),
                ('auth_public_key', models.TextField(max_length=10000)),
            ],
        ),
    ]
