# Generated by Django 4.2.1 on 2023-11-17 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_temptokenmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
