# Generated by Django 4.2.1 on 2024-04-04 23:14

from django.db import migrations, models
import django_sy_framework.custom_auth.validators


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_alter_customauthuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customauthuser',
            name='username',
            field=models.CharField(help_text='Required. 150 characters or fewer. Letters, digits and ./+/-/_ only.', max_length=150, validators=[django_sy_framework.custom_auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
